questions = [
  "Do you serve halal food?",
  "What are the operating hours of the Annex/Harbord location?",
  "What are the operating hours of the Dundas/Junction location?",
  "What is the address of Fantasy Kitchen Co. Annex/Harbord location?",
  "What is the address of Fantasy Kitchen Co. Dundas/Junction location?",
  "What is Fantasy Kitchen Co.?",
  "Who founded Fantasy Kitchen Co.?",
  "What is the mission of Fantasy Kitchen Co.?",
  "What is the vision of Fantasy Kitchen Co.?",
  "What are Fantasy Kitchen Co.’s core values?",
  "What is Fantasy Kitchen Co.’s tagline?",
  "How did Fantasy Kitchen Co. begin?",
  "What is the address of Fantasy Kitchen Co. Annex/Harbord location?",
  "What is the address of Fantasy Kitchen Co. Dundas/Junction location?",
  "What are the operating hours of the Annex/Harbord location?",
  "What are the operating hours of the Dundas/Junction location?",
  "Which Fantasy Kitchen Co. location is closest to me?",
  "What is Fantasy Kitchen Co.’s email?",
  "What is Fantasy Kitchen Co.’s phone number?",
  "How can I contact Fantasy Kitchen Co.?",
  "What food categories does Fantasy Kitchen Co. offer?",
  "What extras and add-ons are available?",
  "Do you offer gluten-free options?",
  "Do you offer vegan or vegetarian items?",
  "Do you serve halal food?",
  "What burgers does Fantasy Kitchen Co. offer?",
  "What are the specialty burgers?",
  "What burger upgrades can I add?",
  "Do burgers come with fries?",
  "What rice bowls are available?",
  "Do you have vegetarian or vegan rice bowls?",
  "What is the price for small and large bowls?",
  "What wraps does Fantasy Kitchen Co. offer?",
  "What is the Calcutta Kathi wrap?",
  "What is the Bombay Frankie wrap?",
  "What makes the Fajita wrap special?",
  "Can I get a gluten-free wrap?",
  "What shawarmas are available?",
  "Do you offer falafel shawarma?",
  "What is the tandoori shawarma?",
  "Can I make a shawarma combo?",
  "What pizzas are available?",
  "What specialty pizzas do you have?",
  "Do you offer gluten-free pizza crust?",
  "Tell me about the Caribbean pizza.",
  "What is the Taj Mahal pizza?",
  "What types of poutine do you offer?",
  "Do you have jerk chicken poutine?",
  "What is included in the original poutine?",
  "What salads does Fantasy Kitchen Co. offer?",
  "Can I add chicken or beef to the salad?",
  "What sides do you offer?",
  "What sauces do Tate Wings come with?",
  "Do you have samosas?",
  "What dessert items do you offer?",
  "What is included in the kids meal?",
  "Do you offer catering?",
  "What does your catering menu include?",
  "Can I customize a catering order?",
  "How do I contact you for catering?",
  "Do you offer delivery?",
  "Which platforms can I order from?",
  "Do you offer free delivery?",
  "How can I order directly online?",
  "What are Fantasy Kitchen Co.’s social media links?",
  "Where can I follow Fantasy Kitchen Co.?",
  "What vegan options do you offer?",
  "What vegetarian items do you have?",
  "What gluten-free items do you offer?",
  "Do you have nut-free options?",
  "What is the Fantasy Kitchen Co. Lunch Box Program?",
  "Is the lunch box program TSBC-approved?",
  "How do parents pre-order lunch boxes?",
  "What dietary options are available for lunch boxes?",
  "What is the Lunch Box menu for October?",
  "What is the Lunch Box menu for December?",
  "Does Fantasy Kitchen Co. offer franchise opportunities?",
  "What support do franchisees receive?",
  "What is the FKC Loyalty Program?",
  "What rewards do loyalty app members get?",
  "How do I download the loyalty app?",
  "What is Fantasy Kitchen Co.’s zero-waste commitment?",
  "How does Fantasy Kitchen Co. support the community?"
]
